# Generated by Django 5.2.12 on 2026-03-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedfile',
            name='downloaded',
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='max_downloads',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
