# Generated by Django 5.2.12 on 2026-03-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0002_remove_sharedfile_downloaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
